# Generated by Django 4.1.1 on 2022-09-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('expired', 'Expired')], default='used', max_length=10),
            preserve_default=False,
        ),
    ]
